local seeds = {
    hemp = 'Hemp',
    saltroot = 'saltroot',
    stagnium = 'stagnium',
    dandelion = 'dandelion',
    eatingplant = 'eatingplant',
    potato = 'potato',
    venomilia = 'venomilia',
    blackthorn = 'blackthorn',
    wheat = 'wheat',
    carrots = 'carrots',
    ferru = 'ferru',
    terrawart = 'terraWart',
    shining = 'shining',
    coffee = 'coffee',
    cyazint = 'cyazint',
    cocoa = 'cocoa',
    tulip = 'tulip',
    cyprium = 'cyprium',
    reed = 'reed',
    aurelia = 'aurelia',
    netherwart = 'netherWart',
    plumbiscus = 'plumbiscus',
    stickreed = 'stickreed',
    melon = 'melon',
    rose = 'rose',
    hops = 'hops',
    pumpkin = 'pumpkin',
    slimeplant = 'Slimeplant',
    tearstalks = 'Tearstalks',
    godofthunder = 'God of Thunder',
    tomato = 'Tomato',
    lemon = 'Lemon',
    diareed = 'Diareed',
    micadia = 'Micadia',
    galvania = 'Galvania',
    tine = 'Tine',
    evilore = 'Evil Ore',
    starwart = 'Starwart',
    onion = 'Onion',
    rape = 'Rape',
    glowheat = 'Glowheat',
    reactoria = 'Reactoria',
    corpseplant = 'Corpseplant',
    plumbilia = 'Plumbilia',
    meatrose = 'Meatrose',
    grape = 'Grape',
    lazulia = 'Lazulia',
    indigo = 'Indigo',
    flax = 'Flax',
    corium = 'Corium',
    cucumber = 'Cucumber',
    quantaria = 'Quantaria',
    trollplant = 'Trollplant',
    enderbloom = 'Enderbloom',
    milkwart = 'Milkwart',
    steeleafranks = 'Steeleafranks',
    pyrolusium = 'Pyrolusium',
    blazereed = 'Blazereed',
    platina = 'Platina',
    scheelinium = 'Scheelinium',
    stargatium = 'Stargatium',
    liveroots = 'Liveroots',
    fertilia = 'Fertilia',
    transformium = 'Transformium',
    eggplant = 'Eggplant',
    coppon = 'Coppon',
    titania = 'Titania',
    creeperweed = 'Creeperweed',
    chilly = 'Chilly',
    zomplant = 'Zomplant',
    nickelback = 'Nickelback',
    bobsyeruncleranks = 'Bobsyeruncleranks',
    oilberries = 'Oilberries',
    olivia = 'Olivia',
    tea = 'Tea',
    argentia = 'Argentia',
    bauxia = 'Bauxia',
    brownmushrooms = 'Brown Mushrooms',
    belladonna = 'Belladonna',
    garnydinia = 'Garnydinia',
    blackstonelilly = 'Black Stonelilly',
    oakbonsai = 'Oak Bonsai',
    glowshroom = 'Glowshroom',
    stingberry = 'Stingberry',
    moss = 'Moss',
    vines = 'Vines',
    sapphirum = 'Sapphirum',
    withereed = 'Withereed',
    redmushrooms = 'Red Mushrooms',
    spidernip = 'Spidernip',
    essenceberry = 'Essence Berry',
    strawberry = 'Strawberry',
    blueberry = 'Blueberry',
    cactus = 'Cactus',
    acaciabonsai = 'Acacia Bonsai',
    greenglowshroom = 'Green Glowshroom',
    primordialberry = 'Primordial Berry',
    berry = 'Berry',
    blightberry = 'Blightberry',
    waterlilly = 'Waterlilly',
    papyrus = 'Papyrus',
    saguarocactus = 'Saguaro Cactus',
    blackberry = 'Blackberry',
    duskberry = 'Duskberry',
    wolfsbane = 'Wolf\'s Bane',
    blueglowshroom = 'Blue Glowshroom',
    bamboo = 'Bamboo',
    embermoss = 'Ember Moss',
    maloberry = 'Maloberry',
    whitestonelilly = 'White Stonelilly',
    sprucebonsai = 'Spruce Bonsai',
    magicalnightshade = 'Magical Nightshade',
    wildcarrots = 'Wild Carrots',
    snowbell = 'Snowbell',
    spaceplant = 'Space Plant',
    darkoakbonsai = 'Dark Oak Bonsai',
    glintweed = 'Glint Weed',
    netherstonelilly = 'Nether Stonelilly',
    sugarbeet = 'Sugar Beet',
    cotton = 'Cotton',
    ivy = 'Ivy',
    garlic = 'Garlic',
    skyberry = 'Skyberry',
    barley = 'Barley',
    eyebulb = 'Eyebulb',
    birchbonsai = 'Birch Bonsai',
    graystonelilly = 'Gray Stonelilly',
    yellowstonelilly = 'Yellow Stonelilly',
    manabean = 'Mana Bean',
    redstonelilly = 'Red Stonelilly',
    glowflower = 'Glowflower',
    goldfishplant = 'Goldfish Plant',
    floweringvines = 'Flowering Vines',
    huckleberry = 'Huckleberry',
    purpleglowshroom = 'Purple Glowshroom',
    spanishmoss = 'Spanish Moss',
    thornvines = 'Thornvines',
    glowingearthcoral = 'Glowing Earth Coral',
    cinderpearl = 'Cinderpearl',
    junglebonsai = 'Jungle Bonsai',
    mandragora = 'Mandragora',
    artichoke = 'Artichoke',
    raspberry = 'Raspberry',
    shimmerleaf = 'Shimmerleaf',
    turnip = 'Turnip',
    weed = 'weed',
    redmushroom = 'redMushroom',
    brownmushroom = 'brownMushroom',
    grass = 'Grass',
    redwheat = 'redwheat',
    ironoreberry = 'Iron Oreberry',
    knightlyoreberry = 'Knightly Oreberry',
    torchberry = 'Torchberry',
    arditeberry = 'Ardite Berry',
    goldoreberry = 'Gold Oreberry',
    aluminiumoreberry = 'Aluminium Oreberry',
    magicmetalberry = 'Magic Metal Berry',
    cobaltberry = 'Cobalt Berry',
    copperoreberry = 'Copper Oreberry',
    tinoreberry = 'Tin Oreberry',
}


local function getSeeds()
    return seeds
end

local function isCorrectSeed(seed)
    seed = string.lower(seed)
    return seeds[string.gsub(seed, '%s+', '')] ~= nil
end

local function isEnoughStats(crop)
    return not (crop.gr > 23 or crop.ga > 31 or crop.re > 2)
end

local function getSeedName(seed)
    return seeds[seed]
end

return {
    getSeeds = getSeeds,
    getSeedName = getSeedName,
    isCorrectSeed = isCorrectSeed,
    isEnoughStats = isEnoughStats
}
